[text]
caption = "Рис.{number}"
task_header = "Завдання №{number}"

[others]
temp_image_file = "temp.png"

[style]
font = "Times New Roman"
font_size = 14

[document]
doctype = "docx"
out_file = "D:/out.docx"
create_new_file = false

[shortcuts]
exit_shortcut = "Ctrl + Q"
add_task_header_shortcut = "Ctrl + Space"
paste_text_from_clipboard_shortcut = "Ctrl + Shift + V"
clear_document_shortcut = "Ctrl + Shift + P"
setup_shortcut = "Ctrl + Shift + S"
screenshot_shortcut = "Shift + Windows + S"
