[shortcuts]
exit = "Ctrl + Shift + Q"
open_document = "Ctrl + Shift + O"
start_current_document = "Ctrl + Shift + D"
new_document = "Ctrl + Shift + N"
clear_current_document = "Ctrl + Shift + C"
paste_clipboard_content = "Ctrl + Shift + V"
open_settings = "Ctrl + Shift + S"
reset_settings = "Ctrl + Shift + R"
add_task_header = "Ctrl + Shift + Space"
screenshot = "Windows + Shift + S"

[document]
current_document = "document.docx"
autoclear_document = false

[style]
font = "Times New Roman"
font_size = 14
caption_format = "Рис. {number}"
task_header_format = "Завдання №{number}"

[ui]
language = "en"
